modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "fastprogress"
version = "${version}"
displayName = "FastProgress"
authors = "Diegus0504"
description = '''
Fast Progress speeds up progression by multiplying block drops when mining. Configure the drop multiplier, whether it applies to generated structure blocks and player/entity-placed blocks, and fine-tune affected blocks via whitelist/blacklist.
'''
logoFile = "assets/fastprogress/icon.png"

[[dependencies.fastprogress]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fastprogress]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fastprogress]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fastprogress]]
modId = "cloth_config"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"
