modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="fastprogress"
version="${version}"
displayName="FastProgress"
authors="Diegus0504"
description='''Fast Progress speeds up progression by multiplying block drops when mining. Configure the drop multiplier, whether it applies to generated structure blocks and player/entity-placed blocks, and fine-tune affected blocks via whitelist/blacklist.'''
logoFile="assets/fastprogress/icon.png"

[[mixins]]
config="fastprogress.mixins.json"

[[mixins]]
config="fastprogress-common.mixins.json"

[[dependencies.fastprogress]]
    modId="neoforge"
    type="required"
    versionRange="[21.11.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastprogress]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastprogress]]
    modId="architectury"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fastprogress]]
    modId="cloth_config"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"
